In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
#chisquare test
data = sns.load_dataset("tips")

In [3]:
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
data[["sex", "smoker"]]

sex smoker
0    Female     No
1      Male     No
2      Male     No
3      Male     No
4    Female     No
..      ...    ...
239    Male     No
240  Female    Yes
241    Male    Yes
242    Male     No
243  Female     No

[244 rows x 2 columns]

In [8]:
#summarisation of data using crosstab
data_table = pd.crosstab(data['sex'], data['smoker'])

In [9]:
data_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [10]:
observed_values = data_table.values

In [11]:
observed_values

array([[60, 97],
       [33, 54]], dtype=int64)

In [14]:
import scipy.stats as stats
stats_test, p, dof, expected_values = stats.chi2_contingency(observed_values)

In [15]:
expected_values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [16]:
#using chisquare critical method
dof = 1

In [17]:
from scipy.stats import chi2

In [18]:
for i in zip(observed_values, expected_values):
    print(i)

(array([60, 97], dtype=int64), array([59.84016393, 97.15983607]))
(array([33, 54], dtype=int64), array([33.15983607, 53.84016393]))


In [19]:
chisquare_test = sum([(0-e)**2/e for o, e in zip(observed_values, expected_values)])

In [20]:
chisquare_test

array([ 93., 151.])

In [21]:
chisquare_stats = chisquare_test[0] + chisquare_test[1]

In [22]:
chisquare_stats

244.0

In [23]:
dof

1

In [25]:
alpha = 0.05

In [26]:
chi2_critical = chi2.ppf(1-alpha, dof)

In [27]:
chi2_critical

3.841458820694124

In [28]:
if chisquare_stats >= chi2_critical:
    print("Reject the null hypothesis, there is a relationship between tow categorical variables")
else:
    print("fail to reject null hypothesis, no relationship")

Reject the null hypothesis, there is a relationship between tow categorical variables


In [30]:
#pvalue method
p_value = 1-chi2.cdf(x = chisquare_stats, df = dof)


In [32]:
if p_value <= 0.05:
    print("Reject the null hypothesis, there is a relationship between tow categorical variables")
else:
    print("fail to reject null hypothesis, no relationship")

Reject the null hypothesis, there is a relationship between tow categorical variables


In [33]:
#No of hours student study daily on a weekly basis
#monday, tuesday... sunday

expected_data = [8, 5, 6, 8, 5, 7, 6]
observed_data = [7, 4, 7, 9, 4, 8, 6]

sum(expected_data), sum(observed_data)

(45, 45)

In [34]:
chisqstats, pvalue = stats.chisquare(observed_values, expected_values)

In [36]:
#using chisquare critical
critical_value = stats.chi2.ppf(1-alpha, dof)

In [41]:
chisqstats = chisqstats[0] + chisqstats[1]

In [43]:
if chisqstats > critical_value:
    print("Reject the null hypothesis")
else:
    print("fail to reject")

fail to reject


In [44]:
#F test
#two workers >> if one worker is more effective than other one




worker1 = [18, 17, 20, 25, 27, 55, 51, 42, 46, 29]
worker2 = [18, 16, 22, 26, 39, 51, 48, 44, 58, 12]

In [46]:
fstats = np.var(worker1) / np.var(worker2)
fstats

0.743155149934811

In [47]:
df1 = len(worker1)-1
df2 = len(worker2)-1

In [48]:
df1

9

In [49]:
df2

9

In [51]:
critical_value = stats.f.ppf(q = 1-alpha, dfn=df1, dfd = df2)

In [52]:
if fstats>critical_value:
    print("Reject the null hypotheis")
else:
    print("fail to reject null hypothesis")

fail to reject null hypothesis


#ANOVA >> compare means of two or more than two sample

An ANOVA test is a type of statistical test used to determine if there is a statistically significant difference between two or more categorical groups by testing for differences of means with variance.

It was developed by the statistician, Ronald Fisher in 1918.

The ANOVA test extends the T and the Z test.

Statistical tests such as T-Test, Z-Test, etc. Most of them are good for univariate situations. On the other hand, the ANOVA test compares the means of different groups and reveals any statistical differences between them.

This test is appropriate when there are three or more groups to compare and establish a difference between them.

Formula:

F = MSB/MSW

MSB = Mean squares between the groups MSW = Mean squares within groups

Example Three different categories of plants can be differentiated on the basis of their weights. A dataset with various plants and their weights are given. Construct a hypothetical test to determine the siginificance of difference among mean of different category of a plant at a significance level of 0.05.

Null Hypothesis: Mean is same for all groups (m1=m2=m3)

Alternate Hypothesis: Mean is not same for atleast one group

In [53]:
df = pd.read_csv('plant.csv')

In [54]:
df

Unnamed: 0  weight group
0            1    4.17  ctrl
1            2    5.58  ctrl
2            3    5.18  ctrl
3            4    6.11  ctrl
4            5    4.50  ctrl
5            6    4.61  ctrl
6            7    5.17  ctrl
7            8    4.53  ctrl
8            9    5.33  ctrl
9           10    5.14  ctrl
10          11    4.81  trt1
11          12    4.17  trt1
12          13    4.41  trt1
13          14    3.59  trt1
14          15    5.87  trt1
15          16    3.83  trt1
16          17    6.03  trt1
17          18    4.89  trt1
18          19    4.32  trt1
19          20    4.69  trt1
20          21    6.31  trt2
21          22    5.12  trt2
22          23    5.54  trt2
23          24    5.50  trt2
24          25    5.37  trt2
25          26    5.29  trt2
26          27    4.92  trt2
27          28    6.15  trt2
28          29    5.80  trt2
29          30    5.26  trt2

In [56]:
df = df.drop("Unnamed: 0", axis = 1)

In [57]:
df

weight group
0     4.17  ctrl
1     5.58  ctrl
2     5.18  ctrl
3     6.11  ctrl
4     4.50  ctrl
5     4.61  ctrl
6     5.17  ctrl
7     4.53  ctrl
8     5.33  ctrl
9     5.14  ctrl
10    4.81  trt1
11    4.17  trt1
12    4.41  trt1
13    3.59  trt1
14    5.87  trt1
15    3.83  trt1
16    6.03  trt1
17    4.89  trt1
18    4.32  trt1
19    4.69  trt1
20    6.31  trt2
21    5.12  trt2
22    5.54  trt2
23    5.50  trt2
24    5.37  trt2
25    5.29  trt2
26    4.92  trt2
27    6.15  trt2
28    5.80  trt2
29    5.26  trt2

In [59]:
groups = df.group.unique()

In [61]:
data = {grp: df["weight"][df.group == grp] for grp in groups}

In [62]:
data

{'ctrl': 0    4.17
 1    5.58
 2    5.18
 3    6.11
 4    4.50
 5    4.61
 6    5.17
 7    4.53
 8    5.33
 9    5.14
 Name: weight, dtype: float64,
 'trt1': 10    4.81
 11    4.17
 12    4.41
 13    3.59
 14    5.87
 15    3.83
 16    6.03
 17    4.89
 18    4.32
 19    4.69
 Name: weight, dtype: float64,
 'trt2': 20    6.31
 21    5.12
 22    5.54
 23    5.50
 24    5.37
 25    5.29
 26    4.92
 27    6.15
 28    5.80
 29    5.26
 Name: weight, dtype: float64}

In [66]:
fstats, pvalue = stats.f_oneway(data['ctrl'], data['trt1'], data['trt2'])

In [67]:
if pvalue <= 0.05:
    print("Reject the null hypothesis")
else:
    print("Fail to reject null hypothesis")

Reject the null hypothesis
